on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - '.editorconfig'
      - 'psalm.xml'
      - 'psalm-baseline.xml'

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      stability: >-
        ['prefer-stable']
